@php($preliminaryStage = $participant->company->joined_competitions()->isPreliminary()->first())
@include('common.partial.detail-property', ['name' => 'Preliminary Stage City', 'value' => object_get($preliminaryStage, 'competition.city') . ' - ' . substr(object_get($preliminaryStage, 'competition.date'), 0 , 10)])
@include('common.partial.detail-property', ['name' => 'Company Name', 'value' => object_get($participant, 'company.name')])
@include('common.partial.detail-property', ['name' => 'Company Description', 'value' => object_get($participant, 'company.description')])
@include('common.partial.photo-property', ['name' => 'Company Logo', 'photo' => object_get($participant, 'company.logo')])
@include('common.partial.detail-property', ['name' => 'Company Size (Employees)', 'value' => object_get($participant, 'company.size')])
@include('common.partial.detail-property', ['name' => 'Year Established', 'value' => object_get($participant, 'company.established')])
@include('common.partial.detail-property', ['name' => 'Type', 'value' => object_get($participant, 'company.type')])
@include('common.partial.detail-property', ['name' => 'Website', 'value' => object_get($participant, 'company.website')])
@include('common.partial.detail-property', ['name' => 'Company Address Line 1', 'value' => object_get($participant, 'company.address')])
@include('common.partial.detail-property', ['name' => 'Company Address Line 2', 'value' => object_get($participant, 'company.address2')])
@include('common.partial.detail-property', ['name' => 'City', 'value' => object_get($participant, 'company.city')])
@include('common.partial.detail-property', ['name' => 'State', 'value' => object_get($participant, 'company.state')])
@include('common.partial.detail-property', ['name' => 'Zip Code', 'value' => object_get($participant, 'company.zip_code')])
